Change Brave span transforming to properly associate spans
honeycombio/beeline-java pull request #87
Opened 2020-10-26 15:19 UTC by tyler-boyd

This does a few things differently:

* Makes the `propagationContext` based on the `traceId` + `parentId` (instead of `spanId`)
* Changes the `hcRootSpan` to force `spanId = $spanId` from the Brave span
* Converts the brave span timestamp to be the same format as HC (I believe this is microseconds -> milliseconds)

Without these changes, we see missing spans and the timestamps appear to be calculated by the HC server when received. With these changes, all spans are linked properly and timestamps appear to be consistent.

Please let me know if any of this does or doesn't make sense; I'm not sure if there was a reason that this transformer _didn't_ re-use the `spanId`/`parentSpanId`/`traceId` exactly from the Brave span.

Thanks!

2020-10-30 14:32 UTC, MikeGoldsmith requested changes
Looks great, thanks for the contribution. Just one minor change to use a local static value for converting the micros to millis.

2020-10-30 14:32 UTC, MikeGoldsmith commented on beeline-spring-boot-sleuth-starter/src/main/java/io/honeycomb/beeline/spring/beans/BraveBeelineReporter.java
> +            hcRootSpan.markStart(startTimestamp/1000, startTimestamp/1000);
```suggestion
            hcRootSpan.markStart(startTimestamp / MICROS_IN_MILLISECOND, startTimestamp / MICROS_IN_MILLISECOND);
```

2020-10-31 22:40 UTC, tyler-boyd commented on beeline-spring-boot-sleuth-starter/src/main/java/io/honeycomb/beeline/spring/beans/BraveBeelineReporter.java
> +            hcRootSpan.markStart(startTimestamp/1000, startTimestamp/1000);
Thanks! I've pushed this change now

2020-11-02 16:30 UTC, MikeGoldsmith approved these changes

2020-11-05 16:33 UTC, MikeGoldsmith commented
Hi @tyler-boyd - looks like we have some test failures that we need to resolve:

```
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   BraveBeelineReporterTest.GIVEN_spanWithAnnotation_EXPECT_rootEventAndEventPerAnnotation:97 Expected found root event and annotations to match expected:<[rootSpan, value2, value]> but was:<[value2, unknown event, value]>
[ERROR]   BraveBeelineReporterTest.GIVEN_spanWithTagAndAnnotation_EXPECT_eventWithFieldDataAndAlsoSpanEvents:200 Expected list of annotations to match expected:<[rootSpan, aValue]> but was:<[unknown event, aValue]>
[ERROR]   BraveBeelineReporterTest.GIVEN_span_EXEPECT_event:78 expected:<00000000000004d2> but was:<null>
[ERROR] Errors: 
[ERROR]   BraveBeelineReporterTest.GIVEN_spanWithAnnotationNotSampled_EXPECT_noAnnotationSent:175 » NullPointer
[INFO] 
[ERROR] Tests run: 9, Failures: 3, Errors: 1, Skipped: 0
```

2020-11-06 12:51 UTC, MikeGoldsmith requested changes
Oops, accidentally approved when I should have requested changes.

2021-01-04 15:23 UTC, MikeGoldsmith commented
Closing this in favour of #95 which includes the original commit and fixes the broken tests.

2021-01-04 15:23 UTC, closed without merging